[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[lib]
path = "src-rs/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"
web-sys = { version = "0.3", features = ["ImageData"] }

[profile.release]
opt-level = 3
lto = true